branch-defaults:
  main:
    environment: my-env-name
    group_suffix: null
global:
  application_name: tushar_portfolio_chatbot-main
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.14 running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
